// LOCALHOST
### Get all contacts
GET http://localhost:3000/users

### Get contact by id
GET http://localhost:3000/users/697ae11b7a580cc6577a79bd

### Create contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
   "firstName": "Anson",
    "lastName": "Hui",
    "email": "friedrice@pokdiuhospital.com",
    "favoriteColor": "Silver",
    "birthday": "21 Jan 2000"
}

### PUT contact
PUT http://localhost:3000/users/697add12ba916572dcd6ae79 HTTP/1.1
content-type: application/json

{
    "firstName": "Ryan",
    "lastName": "Leung",
    "email": "bigmousemouse@sigoku.com",
    "favoriteColor": "Grey",
    "birthday": "3 Jan 2000"
}

### DELETE contact
DELETE http://localhost:3000/users/697abf3583887307b691d6f7